name: dimipay_design_kit
description: "A design kit for Dimipay. Current version is in Alpha, and used in dimipay v2 application."
version: 0.0.3
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

repository: https://github.com/dimipay/dimipay_design_kit.git

flutter:
  fonts:
    - family: SUITv1
      fonts:
        - asset: assets/fonts/SUITv1-Thin.ttf
          weight: 100
        - asset: assets/fonts/SUITv1-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SUITv1-Light.ttf
          weight: 300
        - asset: assets/fonts/SUITv1-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUITv1-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUITv1-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUITv1-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUITv1-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUITv1-Heavy.ttf
          weight: 900