name: dimipay_design_kit
description: "A design kit for Dimipay. Current version is in Alpha, and used in dimipay v2 application & dimipay pos."
version: 0.2.0
homepage: https://dimipay.io

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

assets:
  - assets/images/cards/
  - assets/images/logos/

repository: https://github.com/dimipay/dimipay_design_kit.git
